### PR TITLE
#165 Migrate dagger to ksp

### PR DESCRIPTION
**Pull request by MarekMacko**

### CODE REVIEW

**Review by michal-kucznerowicz — APPROVED** [review]

**Comment by kmaslowiec** [comment]
@MarekMacko same here, shouldn't we re-open the issue if we work on it and add the link to it?

**Comment by MarekMacko** [comment]
> @MarekMacko same here, shouldn't we re-open the issue if we work on it and add the link to it?

Answered here: https://github.com/intive/Picover/pull/182#issuecomment-1713440904

**Review by BorysChajdas — APPROVED** [review]

**Comment by MarekMacko** [comment]
@kmaslowiec  Same here: https://github.com/intive/Picover/pull/182#issuecomment-1713893482

**Review by marcinWisnia — APPROVED** [review]

**Comment by kmaslowiec** [comment]
> 

Approved

**Pull request merged**
