### PR TITLE
#24 Rename strings to follow convention

### PR DESCRIPTION
**Pull request by BorysChajdas**

### CODE REVIEW

**Review by kmaslowiec — APPROVED** [review]

**Comment by kmaslowiec** [comment]
What about names under: PicoverNavHost.kt? 
image

**Comment by BorysChajdas** [comment]
@kmaslowiec that are not resources strings so that not apply to them, but probably it also should be discussed and added to README

**Review by bartek977 — APPROVED** [review]

**Comment by MarekMacko** [comment]
@BorysChajdas Please do not merge it yet

**Comment by MarekMacko** [comment]
@BorysChajdas  Now we're ready to merge, lint error seems to work https://github.com/intive/Picover/actions/runs/4406539218

**Pull request merged**
