### PR TITLE
#24 Reformat code

### PR DESCRIPTION
**Pull request by BorysChajdas**
Intent changes due to our new .editorconfig

### CODE REVIEW

**Comment by michal-kucznerowicz** [comment]
In some cases, the indent is too large. It looks like 8, not 4 (which is recommended).

**Review by michal-kucznerowicz — CHANGES_REQUESTED** [review]
In some cases, the indent is too large. It looks like 8, not 4 (which is recommended).

**Comment by BorysChajdas** [comment]
@michal-kucznerowicz in which file for example?

**Comment by michal-kucznerowicz** [comment]
In diff on github eg `PicoverNavigationBar` but after I checked it locally in AndroidStudio it looks good :D

**Review by michal-kucznerowicz — APPROVED** [review]

**Comment by BorysChajdas** [comment]
@michal-kucznerowicz I think GitHub is displaying tabs and spaces differently that's why it looks like this 😄

**Review by Nataniel-Antosik — APPROVED** [review]

**Pull request merged**
