### PR TITLE
#347 Cleanup Readme - drop "Team" section, fix badges

### PR DESCRIPTION
**Pull request by MarekMacko**

### CODE REVIEW

**Review by marcinWisnia — APPROVED** [review]

**Review by bartek977 — APPROVED** [review]

**Comment by kmaslowiec** [comment]
@MarekMacko Why are we removing the Team section?

**Comment by kmaslowiec** [comment]
@MarekMacko I think the issue number # is wrong

**Comment by MarekMacko** [comment]
> @MarekMacko Why are we removing the Team section?

Because it's not needed in my opinion and just takes a space in README. We should keep only relevant information for our work. If someone wants to check repository contributors then it's available under https://github.com/Android-Guild/Picover/graphs/contributors.

**Comment by MarekMacko** [comment]
> @MarekMacko I think the issue number # is wrong

It's ok. As we discussed, there is no need to create an issue for every small change.

**Comment by MarekMacko** [comment]
@kmaslowiec Let me know if everything is clear. I'll wait for your approval.

**Comment by kmaslowiec** [comment]
> @kmaslowiec Let me know if everything is clear. I'll wait for your approval.

@MarekMacko Good to go.

**Pull request merged**
